services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myprojectart-php
    volumes:
      - '.:/var/www'
    ports:
      - '8000:8000'
      - '9000:9000'
    networks:
      - sail

  nginx:
    image: 'nginx:latest'
    container_name: myprojectart-nginx
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './conf.d/:/etc/nginx/conf.d/:ro'
    ports:
      - '8080:80'
    depends_on:
      - php
    networks:
      - sail
    command:
      - /bin/sh
      - '-c'
      - "nginx -t && nginx -g 'daemon off;'"

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: nt
      POSTGRES_PASSWORD: 123
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    networks:
      - sail

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nata.mark140895@gmail.com
      PGADMIN_DEFAULT_PASSWORD: tulidu140895
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - sail

  react:
    build:
      context: ./frontend
    container_name: myprojectart-react
    ports:
      - '3000:80'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  postgres-data: null
